[package]
name = "disjunctivegraph"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.4"
sattrait = { path = "../sattrait" }
mysatsolver = { path = ".." }
hprof = "0.1"

[dev-dependencies]
itertools = "0.9"
rc2 = { path = "../rc2" }
quickcheck = "0.9"
rand = "0.7"

