[package]
name = "idl"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysatsolver = { path = ".." }
smallvec = "1.3"
sattrait = { path = "../sattrait" }

[dev-dependencies]
itertools = "0.9"
rc2 = { path = "../rc2" }
